# Generated by Django 6.0.3 on 2026-05-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0011_alter_brevet_date_sortie'),
        ('paiements', '0003_remove_paiement_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='id_brevet',
            field=models.OneToOneField(blank=True, db_column='id_brevet', null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.brevet'),
        ),
    ]
