# Generated by Django 6.0.3 on 2026-05-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0005_alter_paiement_id_brevet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
