# Generated by Django 6.0.3 on 2026-04-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id_type',
        ),
        migrations.AddField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('brevet', 'Brevet'), ('demande', 'Demande'), ('recours', 'Recours'), ('paiement', 'Paiement')], default='brevet', max_length=50),
        ),
        migrations.DeleteModel(
            name='TypeDocument',
        ),
    ]
