# Generated by Django 6.0.3 on 2026-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('brevet', 'Brevet'), ('Memoire_Descriptive', 'memoire_descriptive'), ('demande', 'Demande'), ('recours', 'Recours'), ('paiement', 'Paiement')], default='brevet', max_length=50),
        ),
    ]
