# Generated by Django 6.0.3 on 2026-05-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_type_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('brevet', 'Brevet'), ('Memoire Descriptif', 'memoire descriptif'), ('demande', 'Demande'), ('recours', 'Recours'), ('paiement', 'Paiement')], default='brevet', max_length=50),
        ),
    ]
