# Generated by Django 6.0.3 on 2026-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='autre_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
