# Generated by Django 6.0.3 on 2026-05-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_autre_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_sortie_officielle',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
