# Generated by Django 6.0.3 on 2026-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_date_sortie_officielle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_ajout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_sortie_officielle',
            field=models.DateField(blank=True, null=True),
        ),
    ]
