# Generated by Django 6.0.3 on 2026-05-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_document_date_ajout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='montant_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
