# Generated by Django 6.0.3 on 2026-04-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevet',
            name='statut',
            field=models.CharField(choices=[('ACCEPTER', 'ACCEPTER'), ('REFUSER', 'REFUSER'), ('EN_ATTENTE', 'EN_ATTENTE')], default='EN_ATTENTE', max_length=20),
        ),
    ]
