# Generated by Django 6.0.3 on 2026-04-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0004_brevet_id_dep_brevet_id_inv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brevet',
            name='id_dep',
        ),
        migrations.RemoveField(
            model_name='brevet',
            name='id_inv',
        ),
    ]
