# Generated by Django 6.0.3 on 2026-04-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0005_remove_brevet_id_dep_remove_brevet_id_inv'),
    ]

    operations = [
        migrations.AddField(
            model_name='brevet',
            name='id_dep',
            field=models.ForeignKey(db_column='id_deposant', null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.deposant'),
        ),
        migrations.AddField(
            model_name='brevet',
            name='id_inv',
            field=models.ManyToManyField(related_name='inventeur', to='brevets.inventeur'),
        ),
    ]
