# Generated by Django 6.0.3 on 2026-04-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0006_brevet_id_dep_brevet_id_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandebrevet',
            name='date_reception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandebrevet',
            name='lieu_reception',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='demandebrevet',
            name='prepose_reception',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
