# Generated by Django 6.0.3 on 2026-04-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0007_alter_demandebrevet_date_reception_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventeur',
            name='id_demande',
        ),
        migrations.AddField(
            model_name='inventeur',
            name='id_demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventeurs', to='brevets.demandebrevet'),
        ),
    ]
