# Generated by Django 6.0.3 on 2026-05-01 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0008_remove_inventeur_id_demande_inventeur_id_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevet',
            name='id_demande',
            field=models.OneToOneField(blank=True, db_column='id_demande', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brevet', to='brevets.demandebrevet'),
        ),
    ]
