# Generated by Django 6.0.3 on 2026-05-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0009_alter_brevet_id_demande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brevet',
            name='id_demande',
        ),
        migrations.RemoveField(
            model_name='brevet',
            name='id_dep',
        ),
        migrations.RemoveField(
            model_name='brevet',
            name='id_inv',
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='id_brevet',
            field=models.OneToOneField(blank=True, db_column='id_brevet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande', to='brevets.brevet'),
        ),
    ]
