# Generated by Django 6.0.3 on 2026-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0010_remove_brevet_id_demande_remove_brevet_id_dep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevet',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
