# Generated by Django 6.0.3 on 2026-05-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0011_alter_brevet_date_sortie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandebrevet',
            old_name='id',
            new_name='createur',
        ),
    ]
