# Generated by Django 6.0.3 on 2026-05-07 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0012_rename_id_demandebrevet_createur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandebrevet',
            name='createur',
            field=models.ForeignKey(db_column='createur', on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
