# Generated by Django 6.0.3 on 2026-05-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0013_alter_demandebrevet_createur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandebrevet',
            old_name='createur',
            new_name='id',
        ),
    ]
