# Generated by Django 6.0.3 on 2026-05-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0014_rename_createur_demandebrevet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_abrege',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_cession',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_copie_int',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_dessins_dup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_dessins_orig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_memoire_fr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_memoire_fr_dup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_memoire_nat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_pouvoir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_priorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='piece_titre',
            field=models.BooleanField(default=False),
        ),
    ]
