# Generated by Django 6.0.3 on 2026-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0015_demandebrevet_piece_abrege_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebrevet',
            name='titre_dem',
            field=models.TextField(default='', null=True),
        ),
    ]
