# Generated by Django 6.0.3 on 2026-05-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0016_demandebrevet_titre_dem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevet',
            name='date_depo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brevet',
            name='num_brevet',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='brevet',
            name='num_depo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='brevet',
            name='titre',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brevet',
            name='titulaire',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
