# Generated by Django 6.0.3 on 2026-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0017_alter_brevet_date_depo_alter_brevet_num_brevet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevet',
            name='num_depo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
