# Generated by Django 6.0.3 on 2026-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0018_alter_brevet_num_depo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandebrevet',
            name='date_pouvoir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
