# Generated by Django 6.0.3 on 2026-05-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0019_alter_demandebrevet_date_pouvoir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandebrevet',
            name='titre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
