# Generated by Django 6.0.3 on 2026-05-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0020_alter_demandebrevet_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevet',
            name='num_brevet',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
