# Generated by Django 6.0.3 on 2026-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0021_alter_brevet_num_brevet'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebrevet',
            name='num_brevet',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
