# Generated by Django 6.0.3 on 2026-05-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0022_demandebrevet_num_brevet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandebrevet',
            name='num_brevet',
        ),
        migrations.AlterField(
            model_name='brevet',
            name='num_depo',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
