# Generated by Django 6.0.3 on 2026-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0023_remove_demandebrevet_num_brevet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brevet',
            name='num_brevet',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
