# Generated by Django 6.0.2 on 2026-04-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_utilisateur_date_ajout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="id_role",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
