# Generated by Django 6.0.3 on 2026-05-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recours', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recours',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
