# Generated by Django 6.0.3 on 2026-05-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0011_alter_brevet_date_sortie'),
        ('recours', '0003_alter_recours_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recours',
            name='id_brevet',
            field=models.ForeignKey(blank=True, db_column='id_brevet', null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.brevet'),
        ),
    ]
